# Generated by Django 3.1.2 on 2020-11-03 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('0', 'SAP1'), ('1', 'SAP2'), ('2', 'SAP3'), ('3', 'SAP4')], default='0', max_length=20)),
                ('process', models.CharField(choices=[('0', 'PO create'), ('1', 'PO change'), ('2', 'PO close'), ('3', 'Query')], default='0', max_length=20)),
                ('business_segment', models.CharField(choices=[('0', 'BU1'), ('1', 'BU2'), ('2', 'BU3'), ('3', 'BU4')], default='0', max_length=20)),
                ('starting_date', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True)),
                ('days_to_complete', models.SmallIntegerField()),
                ('deadline', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True)),
                ('ageing', models.CharField(choices=[('0', 'current'), ('1', 'aged'), ('2', 'urgent')], default='0', max_length=20)),
                ('ticket_number', models.SmallIntegerField()),
                ('email_subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('0', 'action needed'), ('1', 'pending'), ('2', 'completed')], default='0', max_length=20)),
                ('name', models.CharField(choices=[('0', 'Colleague1'), ('1', 'Colleague2'), ('2', 'Colleague3')], default='0', max_length=50)),
                ('contact', models.CharField(max_length=200)),
                ('supplier', models.CharField(max_length=200)),
                ('supplier_number', models.SmallIntegerField()),
                ('supplier_email', models.EmailField(max_length=254)),
                ('action_started', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True)),
                ('output_number', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True)),
                ('pass_or_fail', models.CharField(choices=[('0', 'N/A'), ('1', 'PASS'), ('2', 'FAIL')], default='0', max_length=50)),
                ('editing', models.BooleanField(default=False)),
            ],
        ),
    ]
