# Generated by Django 3.1.2 on 2020-11-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('0', 'Process1'), ('1', 'Process2'), ('2', 'Process3'), ('3', 'Process4')], default='0', max_length=20),
        ),
    ]
