# Generated by Django 3.1.2 on 2020-11-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_auto_20201103_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='system',
            field=models.CharField(choices=[('0', 'System1'), ('1', 'System2'), ('2', 'System3'), ('3', 'System4')], default='0', max_length=20),
        ),
    ]
