# Generated by Django 3.1.2 on 2020-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_auto_20201103_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='days_to_complete',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='email_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='pass_or_fail',
            field=models.CharField(blank=True, choices=[('0', 'N/A'), ('1', 'PASS'), ('2', 'FAIL')], default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='supplier_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
